AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/

Documentation:
    Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

require:
  - rubocop-minitest
  - rubocop-rails